### ISSUE TITLE
CMySQL missing

### ISSUE THREAD

**Issue by rezahussain** [simplepanda/SimpleSQL#1]
Hello,

Can you assist me in getting the CMySQL module linked into the build?

admin2@admin2:~/Desktop/RS1DataPreparer/Sources$ swift build -Xcc -fblocks -Xcc -I/usr/include/mysql -Xlinker -L/usr/lib/x86_64-linux-gnu
Compile Swift Module 'SimpleSQL' (10 sources)
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
/home/admin2/Desktop/RS1DataPreparer/Packages/SimpleSQL-0.4.4/Sources/SSQuery.swift:22:8: error: missing required module 'CMySQL'
import MySQL
       ^
<unknown>:0: error: build had 1 command failures
error: exit(1): /home/admin2/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu15.10/usr/bin/swift-build-tool -f /home/admin2/Desktop/RS1DataPreparer/.build/debug.yaml
admin2@admin2:~/Desktop/RS1DataPreparer/Sources$

**Comment by simplepanda** [comment]
Strange. Can you post your Package.swift contents?

**Comment by rezahussain** [comment]
Hello,

Here is the contents of my Package.swift

import PackageDescription

let package = Package(
    name:"R1DataPreparer",
    targets:[],
    dependencies: [
        

        .Package(url: "https://github.com/simplepanda/SimpleSQL.git", majorVersion: 0, minor: 4),
	
	

        
        
    ]
)

**Comment by simplepanda** [comment]
Strange.

Ok, try changing it to this:

```.Package(url: "https://github.com/simplepanda/SimpleSQL.git", majorVersion: 0)```

(So, get rid of the minor: 4 parameter).

Then, do this:

```
$ swift build --clean
$ rm -rf .build
$ rm -rf Packages
$ swift build -Xcc -fblocks -Xcc -I/usr/include/mysql -Xlinker -L/usr/lib/x86_64-linux-gnu
```

That should flush the dependencies. 

Make sure it's also checking out the MySQL module when it builds, as MySQL is a dependency of SimpleSQL (SimpleSQL declares it in it's own Package.swift so it should be automatically pulled by ```swift build``` as part of the dependency resolution).

**Comment by rezahussain** [comment]
wow that fixed it, thanks!

**Comment by simplepanda** [comment]
No worries.
